### ISSUE TITLE
Help Wanted: Reformatting Documentation

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixijs#7159]
## Overview

Recently, we converted our documentation to use [webdoc](https://github.com/webdoc-labs/webdoc/) instead of JSDoc. The advantage of this switch is that much more can be inferred from the TypeScript. Right now, the documentation has type cruft from JSDoc, making it kinda unnecessarily verbose. Also, the documentation for members was historically placed within the constructor, but we'd like to move it to the root of the class where the TypeScript member is declared.

We are looking for help! These are straightforward fixes, but require many hands. If you have a free moment, please consider updating a class below (keep in mind that not all classes will need converting).

💥  **BONUS POINTS FOR:**

* Adding missing descriptions
* Improving descriptions
* Fixing typos

**Please please please _no code or logic changes_.**

## Goals

* Make the constructor easier to read 
* Expose documentation in typings
* Remove redundant information in docs such as access-modifiers and types

## Style Rules

* Add initial values and member docs to the class-level
* Remove redundant access modifiers (public/private/protected)
* Remove type declarations for all private
* Make docs single line, if possible
* Remove redundant types for members
* Make sure that any default values or types with `PIXI.*` are retained (or else Webdoc won't link)

### Example 
Old format:
```javascript
/**	
 * Setting this to true will visually show the divs.	
 *	
 * @type {boolean}
 * @public
 * @default false
 */	
this.debug = false;
```
New format:
```typescript
/** Setting this to true will visually show the divs. */
public debug = false;
```

Here's an example I created with AccessibilityManager #7113 

### Classes To Convert

- [x] packages/accessibility/src/AccessibilityManager.ts #7113
- [x] packages/app/src/Application.ts #7160
- [x] packages/app/src/ResizePlugin.ts #7160
- [x] packages/basis/src/BasisLoader.ts #7584 
- [x] packages/basis/src/TranscoderWorker.ts #7584 
- [x] packages/canvas/canvas-extract/src/CanvasExtract.ts #7584 
- [x] packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.ts #7584 
- [x] packages/canvas/canvas-mesh/src/CanvasMeshRenderer.ts #7584 
- [x] packages/canvas/canvas-prepare/src/CanvasPrepare.ts #7584 
- [x] packages/canvas/canvas-renderer/src/CanvasRenderer.ts #7584 
- [x] packages/canvas/canvas-renderer/src/utils/CanvasMaskManager.ts #7584 
- [x] packages/canvas/canvas-sprite/src/CanvasSpriteRenderer.ts #7584 
- [x] packages/compressed-textures/src/loaders/CompressedTextureLoader.ts #7584 
- [x] packages/compressed-textures/src/loaders/DDSLoader.ts #7584 
- [x] packages/compressed-textures/src/loaders/KTXLoader.ts #7584 
- [x] packages/compressed-textures/src/resources/CompressedTextureResource.ts #7584 
- [x] packages/core/src/Renderer.ts #7802 
- [x] packages/core/src/System.ts
- [x] packages/core/src/batch/AbstractBatchRenderer.ts #7803
- [x] packages/core/src/batch/BatchDrawCall.ts #7910
- [x] packages/core/src/batch/BatchGeometry.ts #7910
- [x] packages/core/src/batch/BatchPluginFactory.ts #7910
- [x] packages/core/src/batch/BatchShaderGenerator.ts #7910
- [x] packages/core/src/batch/BatchSystem.ts #7910
- [x] packages/core/src/batch/BatchTextureArray.ts #7910
- [x] packages/core/src/batch/ObjectRenderer.ts #7910
- [x] packages/core/src/context/ContextSystem.ts #7885
- [x] packages/core/src/filters/Filter.ts #7992
- [x] packages/core/src/filters/FilterState.ts #7992
- [x] packages/core/src/filters/FilterSystem.ts #7992
- [x] packages/core/src/filters/spriteMask/SpriteMaskFilter.ts #7992
- [x] packages/core/src/framebuffer/Framebuffer.ts #8161 
- [x] packages/core/src/framebuffer/FramebufferSystem.ts #8161
- [x] packages/core/src/framebuffer/GLFramebuffer.ts #8161
- [x] packages/core/src/geometry/Attribute.ts #7963
- [x] packages/core/src/geometry/Buffer.ts #7963
- [x] packages/core/src/geometry/Geometry.ts #7963
- [x] packages/core/src/geometry/GeometrySystem.ts #7963
- [x] packages/core/src/geometry/GLBuffer.ts
- [x] packages/core/src/geometry/ViewableBuffer.ts #8162
- [x] packages/core/src/mask/AbstractMaskSystem.ts #7817
- [x] packages/core/src/mask/MaskData.ts #7817
- [x] packages/core/src/mask/MaskSystem.ts #7817
- [x] packages/core/src/mask/ScissorSystem.ts #7817
- [x] packages/core/src/mask/StencilSystem.ts #7817
- [x] packages/core/src/projection/ProjectionSystem.ts #7884
- [x] packages/core/src/renderTexture/BaseRenderTexture.ts #8162
- [x] packages/core/src/renderTexture/RenderTexture.ts #7882
- [x] packages/core/src/renderTexture/RenderTexturePool.ts #7882
- [x] packages/core/src/renderTexture/RenderTextureSystem.ts #7882
- [x] packages/core/src/shader/GLProgram.ts #8162
- [x] packages/core/src/shader/Program.ts #7881
- [x] packages/core/src/shader/Shader.ts #7881
- [x] packages/core/src/shader/ShaderSystem.ts #7881
- [x] packages/core/src/shader/UniformGroup.ts #8162
- [x] packages/core/src/state/State.ts #7883
- [x] packages/core/src/state/StateSystem.ts #7786 
- [x] packages/core/src/textures/BaseTexture.ts #8163
- [x] packages/core/src/textures/GLTexture.ts #8163
- [x] packages/core/src/textures/Texture.ts #8163
- [x] packages/core/src/textures/TextureGCSystem.ts #8163
- [x] packages/core/src/textures/TextureMatrix.ts #8164
- [x] packages/core/src/textures/TextureSystem.ts #8164
- [x] packages/core/src/textures/TextureUvs.ts #8164
- [x] packages/core/src/textures/resources/ArrayResource.ts #7993
- [x] packages/core/src/textures/resources/BaseImageResource.ts #7993
- [x] packages/core/src/textures/resources/BufferResource.ts #7993
- [x] packages/core/src/textures/resources/CanvasResource.ts #7993
- [x] packages/core/src/textures/resources/CubeResource.ts #7993
- [x] packages/core/src/textures/resources/DepthResource.ts #7993
- [x] packages/core/src/textures/resources/ImageBitmapResource.ts #7993
- [x] packages/core/src/textures/resources/ImageResource.ts #7993
- [x] packages/core/src/textures/resources/SVGResource.ts #7993
- [x] packages/core/src/textures/resources/VideoResource.ts #7993
- [x] packages/core/src/utils/Quad.ts #8166
- [x] packages/core/src/utils/QuadUv.ts #8166
- [x] packages/display/src/Bounds.ts #8166
- [x] packages/display/src/Container.ts #8166
- [x] packages/display/src/DisplayObject.ts
- [x] packages/extract/src/Extract.ts #8167
- [x] packages/filters/filter-alpha/src/AlphaFilter.ts #7804
- [x] packages/filters/filter-blur/src/BlurFilter.ts #7804
- [x] packages/filters/filter-blur/src/BlurFilterPass.ts #8167
- [x] packages/filters/filter-color-matrix/src/ColorMatrixFilter.ts #7942
- [x] packages/filters/filter-displacement/src/DisplacementFilter.ts #7942
- [x] packages/filters/filter-fxaa/src/FXAAFilter.ts #7942
- [x] packages/filters/filter-noise/src/NoiseFilter.ts #7942
- [x] packages/graphics/src/Graphics.ts #8168
- [x] packages/graphics/src/GraphicsData.ts #8168
- [x] packages/graphics/src/GraphicsGeometry.ts #8168
- [x] packages/graphics/src/styles/FillStyle.ts #8168
- [x] packages/graphics/src/styles/LineStyle.ts #8168
- [x] packages/graphics/src/utils/ArcUtils.ts #8169
- [x] packages/graphics/src/utils/BatchPart.ts #8169
- [x] packages/graphics/src/utils/BezierUtils.ts #8169
- [x] packages/graphics/src/utils/QuadraticUtils.ts #8169
- [x] packages/graphics/src/utils/Star.ts #8169
- [x] packages/interaction/src/InteractionData.ts #8170
- [x] packages/interaction/src/InteractionEvent.ts #8170
- [x] packages/interaction/src/InteractionManager.ts #8170
- [x] packages/interaction/src/InteractionTrackingData.ts #8170
- [x] packages/interaction/src/TreeSearch.ts #8170
- [x] packages/loaders/src/AppLoaderPlugin.ts
- [x] packages/loaders/src/Loader.ts
- [x] packages/loaders/src/TextureLoader.ts
- [x] packages/math/src/Matrix.ts #7905
- [x] packages/math/src/ObservablePoint.ts #7905
- [x] packages/math/src/Point.ts #7414
- [x] packages/math/src/Transform.ts #7787
- [x] packages/math/src/shapes/Circle.ts #7788
- [x] packages/math/src/shapes/Ellipse.ts #7788
- [x] packages/math/src/shapes/Polygon.ts #7966
- [x] packages/math/src/shapes/Rectangle.ts #7876 
- [x] packages/math/src/shapes/RoundedRectangle.ts #8171
- [x] packages/mesh/src/Mesh.ts #7965
- [x] packages/mesh/src/MeshBatchUvs.ts #8165
- [x] packages/mesh/src/MeshGeometry.ts #8165
- [x] packages/mesh/src/MeshMaterial.ts #8165
- [x] packages/mesh-extras/src/NineSlicePlane.ts #7812
- [x] packages/mesh-extras/src/SimpleMesh.ts #7812
- [x] packages/mesh-extras/src/SimplePlane.ts #7812
- [x] packages/mesh-extras/src/SimpleRope.ts #7812
- [x] packages/mesh-extras/src/geometry/PlaneGeometry.ts
- [x] packages/mesh-extras/src/geometry/RopeGeometry.ts #8165
- [x] packages/mixin-cache-as-bitmap/src/index.ts
- [x] packages/particles/src/ParticleBuffer.ts #8058
- [x] packages/particles/src/ParticleContainer.ts #8058
- [x] packages/particles/src/ParticleRenderer.ts #8058
- [x] packages/prepare/src/BasePrepare.ts #7805
- [x] packages/prepare/src/CountLimiter.ts #7805
- [x] packages/prepare/src/Prepare.ts #7805
- [x] packages/prepare/src/TimeLimiter.ts #8010
- [x] packages/runner/src/Runner.ts #7811 
- [x] packages/sprite/src/Sprite.ts #7841 
- [x] packages/sprite-animated/src/AnimatedSprite.ts #7909
- [x] packages/sprite-tiling/src/TilingSprite.ts #7806
- [x] packages/sprite-tiling/src/TilingSpriteRenderer.ts #7806
- [x] packages/spritesheet/src/Spritesheet.ts #7906
- [x] packages/spritesheet/src/SpritesheetLoader.ts #7907
- [x] packages/text/src/Text.ts #7842
- [x] packages/text/src/TextMetrics.ts #7842
- [x] packages/text/src/TextStyle.ts #7843
- [x] packages/text-bitmap/src/BitmapFont.ts #7908
- [x] packages/text-bitmap/src/BitmapFontData.ts #8009
- [x] packages/text-bitmap/src/BitmapFontLoader.ts #8009
- [x] packages/text-bitmap/src/BitmapText.ts #8009
- [x] packages/text-bitmap/src/formats/TextFormat.ts #8009
- [x] packages/text-bitmap/src/formats/XMLFormat.ts #8009
- [x] packages/text-bitmap/src/formats/XMLStringFormat.ts #8009
- [x] packages/ticker/src/Ticker.ts - **In Progress** #7199 
- [x] packages/ticker/src/TickerListener.ts - **In Progress** #7199 
- [x] packages/ticker/src/TickerPlugin.ts #7160
- [x] packages/utils/src/media/CanvasRenderTarget.ts - **In Progress** #7199

**Comment by endel** [comment]
Hey :wave:, I was going to join this effort, but I'm not sure the `webdoc` is currently behaving as expected:

- I've replaced `@member {string[][]}` comments with its TypeScript type equivalent, but they don't seem to appear on the generated docs
- Most `constructor` currently only have JSDoc to describe argument types, even when they're already provided by TypeScript

After running `npm run webdoc`, this is the output I've seen: (You can see my changes at https://github.com/endel/pixi.js/commit/15cbbe5ad9eab3da8d8993abb9af29d6f24f064e)

<img width="960" alt="Screen Shot 2021-01-16 at 18 08 26" src="https://user-images.githubusercontent.com/130494/104823597-176fb680-582a-11eb-8d03-f2a1e127bdc9.png">

Please let me know if I'm missing something!

**Comment by bigtimebuddy** [comment]
@endel thanks! You removed the constructor params we need to keep that. With no doc for the constructor, it'll be ignored. Also, for more complex types like string[][], we should keep that as `@type`. Webdoc is good as inferring types for simple things, but not more complex stuff. Maybe @SukantPal can look at that specific example.

**Comment by SukantPal** [comment]
Type inference is for primitives only right now.

**Comment by SukantPal** [comment]
There are two workarounds:

1. preferred
```ts
/** Description */
public ASCII: string[][] = [['string']];
```

2. not preferred
```ts
/**
 * Description
 * @type {string[][]}
 */
public ASCII = [['string']];
```

**Comment by snowinmars** [comment]
Hi. Just saying that using `"pixi.js": "^6.0.1",` I have the following ambiguity.
![image](https://user-images.githubusercontent.com/5859735/117937825-3ef7fc80-b2bb-11eb-97f9-2b90e47fd39d.png)

Ty for your work)

**Comment by bigtimebuddy** [comment]
Little over a year to complete this task.
Great work @ShukantPal and deep thanks for all your working in making this happen.
